# This workflow will reformat the code with black
name: Black

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Black Code Formatter
      uses: lgeiger/black-action@1.0.1
      with:
        args: .
    - name: Create-pull-request
      uses: peter-evans/create-pull-request@v3
